-- MySQL Script generated by MySQL Workbench
-- Mon Nov 20 12:04:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema collinson_test_parkerh
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `collinson_test_parkerh` ;

-- -----------------------------------------------------
-- Schema collinson_test_parkerh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `collinson_test_parkerh` DEFAULT CHARACTER SET utf8 ;
USE `collinson_test_parkerh` ;

-- -----------------------------------------------------
-- Table `collinson_test_parkerh`.`runners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `collinson_test_parkerh`.`runners` ;

CREATE TABLE IF NOT EXISTS `collinson_test_parkerh`.`runners` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `collinson_test_parkerh`.`races`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `collinson_test_parkerh`.`races` ;

CREATE TABLE IF NOT EXISTS `collinson_test_parkerh`.`races` (
  `id` INT NOT NULL,
  `event` VARCHAR(45) NULL,
  `winner_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_races_runners_idx` (`winner_id` ASC) VISIBLE,
  CONSTRAINT `fk_races_runners`
    FOREIGN KEY (`winner_id`)
    REFERENCES `collinson_test_parkerh`.`runners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `collinson_test_parkerh`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `collinson_test_parkerh`.`users` ;

CREATE TABLE IF NOT EXISTS `collinson_test_parkerh`.`users` (
  `user_id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `collinson_test_parkerh`.`training_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `collinson_test_parkerh`.`training_details` ;

CREATE TABLE IF NOT EXISTS `collinson_test_parkerh`.`training_details` (
  `user_training_id` INT NOT NULL,
  `user_id` INT NULL,
  `training_id` INT NULL,
  `training_date` DATETIME NULL,
  PRIMARY KEY (`user_training_id`),
  INDEX `fk_training_details_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_training_details_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `collinson_test_parkerh`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
